name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Install Toolchain
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose --features="fail-on-warnings"
      - name: Test
        run: cargo test --verbose --features="fail-on-warnings"
      - name: Docs
        run: cargo doc --no-deps --features="fail-on-warnings"

  stylecheck:
    runs-on: ubuntu-24.04
    container: librepcb/librepcb-dev:devtools-4
    steps:
      - uses: actions/checkout@v4
      - name: Stylecheck
        run: .github/workflows/stylecheck.sh
      - name: Cargo Clippy
        run: cargo clippy --features="fail-on-warnings"
      - name: Reuse Lint
        run: reuse --suppress-deprecation lint
